apiVersion: skaffold/v2alpha1
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:0.0.1"
  artifacts:
  - image: tinytelly/camunda-ee-postgresql
    context: ./build/postgres/image
test:
  - image: camunda-ee-postgresql
    structureTests:
      - './build/postgres/postgresql-tests.yaml'
deploy:
  helm:
    releases:
    - name: camunda-helm
      chartPath: ./camunda-helm
      values:
        image: camunda-ee-postgresql      