apiVersion: skaffold/v2alpha1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: camunda-ee-postgresql
    context: ./build/postgres/image
  local:
    push: false
test:
  - image: camunda-ee-postgresql
    structureTests:
      - './build/postgres/postgresql-tests.yaml'
deploy:
  helm:
    releases:
    - name: camunda-helm
      chartPath: ./camunda-helm
      skipBuildDependencies: false
      values:
        image: camunda-ee-postgresql      