apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.camunda.name }}-deployment
  labels:
    {{- include "camunda-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "camunda-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "camunda-helm.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "camunda-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.camunda.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.camunda.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.camunda.applicationPort }}
              protocol: TCP
          env:
            - name: DB_URL
              value: jdbc:postgresql://{{ .Values.postgresql.name }}-service:{{ .Values.postgresql.applicationPort }}/{{ required "postgresql.postgresqlDatabase " .Values.postgresql.postgresqlDatabase  }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: camunda-database-credentials
                  key: username
            - name: DB_PASSWORD
              secretKeyRef:
                  name: camunda-database-credentials
                  key: password
            - name: DB_DRIVER
              value: org.postgresql.Driver
          livenessProbe:
            httpGet:
              path: {{ required "livenessPath" .Values.livenessPath  }}
              port: {{ .Values.camunda.applicationPort }}
            initialDelaySeconds: {{  required "livenessDelay " .Values.livenessDelay  }}
            timeoutSeconds: {{  required "livenessTimeout " .Values.livenessTimeout  }}
            periodSeconds: {{  required "livenessPeriod " .Values.livenessPeriod  }}
            failureThreshold: {{  required "livenessFailureThreshold  " .Values.livenessFailureThreshold   }}
          readinessProbe:
            httpGet:
              path: {{ required "readinessPath" .Values.readinessPath   }}
              port: {{ .Values.camunda.applicationPort }}
            initialDelaySeconds: {{  required "readinessDelay " .Values.readinessDelay  }}
            timeoutSeconds: {{  required "readinessTimeout " .Values.readinessTimeout  }}
            periodSeconds: {{  required "readinessPeriod " .Values.readinessPeriod  }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgresql.name }}-deployment
  labels:
    {{- include "camunda-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgresql.replicaCount }}
  selector:
    matchLabels:
      {{- include "camunda-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "camunda-helm.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "camunda-helm.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.postgresql.repository }}:{{ .Values.postgresql.version }}"
          imagePullPolicy: {{ .Values.camunda.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.postgresql.applicationPort  }}
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: camunda-database-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              secretKeyRef:
                  name: camunda-database-credentials
                  key: password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
