apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.camunda.name }}-service
  labels:
    {{- include "camunda-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.camunda.service.type }}
  ports:
    - port: {{ .Values.camunda.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "camunda-helm.selectorLabels" . | nindent 4 }}


---


apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name }}-service
  labels:
    {{- include "camunda-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "camunda-helm.selectorLabels" . | nindent 4 }}